[package]
name = "poseidon-ark-no-std"
version = "0.0.1"
authors = ["2nado <https://github.com/2nado>"]
edition = "2021"
license = "Apache-2.0"
description = "Poseidon hash implementation"
repository = "https://github.com/2nado/poseidon-ark/tree/no-std"
readme = "README.md"

[dependencies]
ark-ff = "0.4.0"
ark-bn254 = { version = "0.4.0" }
ark-std = { version = "0.4.0", default-features = false }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_poseidon_hash"
harness = false

[features]
default = ["std"]
std = [
    "ark-std/std",
    "ark-ff/std",
    "ark-bn254/std",
]
